# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"O\n\x13ServoUltrasonicData\x12\x12\n\nposition_1\x18\x01 \x01(\x02\x12\x12\n\nposition_2\x18\x02 \x01(\x02\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\"E\n\x06Status\x12\x13\n\x0block_motors\x18\x01 \x01(\x08\x12\x12\n\nfire_laser\x18\x02 \x01(\x08\x12\x12\n\nmotor_mode\x18\x03 \x01(\x08\"Q\n\x0c\x43ombinedData\x12(\n\nservo_data\x18\x01 \x01(\x0b\x32\x14.ServoUltrasonicData\x12\x17\n\x06status\x18\x02 \x01(\x0b\x32\x07.Statusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVOULTRASONICDATA._serialized_start=17
  _SERVOULTRASONICDATA._serialized_end=96
  _STATUS._serialized_start=98
  _STATUS._serialized_end=167
  _COMBINEDDATA._serialized_start=169
  _COMBINEDDATA._serialized_end=250
# @@protoc_insertion_point(module_scope)
